Dump vm log on failure

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -77,7 +77,9 @@ jobs:
           set -x
           set -e
 
-          screen -d -m -S vm mkosi vm -- -uuid $(uuidgen)
+          #screen -d -m -S vm 
+          mkosi vm -- -uuid $(uuidgen) > vm.log 2>&1 &
+          pid=$!
 
           success=0
           for try in {1..10}
@@ -89,7 +91,15 @@ jobs:
                   fi
                   sleep 5
           done
-          test $success -eq 1
+
+          if [ test $success -eq 1 ]
+          then
+                  echo "mkosi ssh succeeded"
+          else
+                  echo "mkosi ssh failed"
+                  cat vm.log
+                  exit 1
+          fi
           mkosi ssh -- shutdown -h now || true
           sleep 5
 
